version: "3.8"

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-gateway
    ports:
      - "4567:4567"
    volumes:
      - whatsapp-auth:/app/auth # Gunakan named volume
    environment:
      - PORT=4567
      - NODE_ENV=production
      - ALLOWED_ORIGINS=*
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  whatsapp-auth:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/on/host/auth # Ganti dengan path absolut di VPS
